### ISSUE TITLE
add link on `http://ehlfi.niflh.net/` to github pages

### ISSUE THREAD

**Issue by hirosassa** [xenolay/calculus_on_manifolds#13]
I think it is better to add link to github pages from your page `http://ehlfi.niflh.net/`.

**Comment by xenolay** [comment]
Thanks for your suggestion! I've just edited.

![スクリーンショット 2021-09-12 午後3 45 30](https://user-images.githubusercontent.com/7780333/132976748-052a6d27-361d-4024-a0d3-cac37943c072.png)

**Comment by hirosassa** [comment]
Thank you for the rapid reply and apply!
